const SITE = 'https://codex-mochi.mochilabo.workers.dev';
const RECORDING = 'https://mochiketu2026.substack.com/p/codex';
const KEY = 'mochi-easy-start-preview-v1';
const main = document.querySelector('main');
const dialog = document.querySelector('dialog');
const creationPrompt = `かわいいカピバラの画像を、まず1枚だけ作ってください。
絵本に出てくるような、やわらかな色鉛筆と水彩の雰囲気。
まるい体、短い手足、小さな耳、眠そうでやさしい目。薄い茶色の体に、濃い茶色の輪郭。正面を向いて、片手を振っています。
全身を画面に入れ、まわりに余白を残してください。文字、小物、床、影は入れず、背景は透過PNGにしてください。
内蔵の画像生成を使ってください。使えない場合は、その旨と次にできることを教えてください。
完成画像を表示し、保存したファイルを開けるリンクも案内してください。
説明は短い日本語で、難しい言葉を避けてください。私に操作をお願いするときは、一度に1つずつ案内してください。`;
const supportPrompt = `この会話では、はじめての人にも伝わる短い日本語で案内してください。
難しい言葉は避けて、私が操作することは一度に1つだけ伝えてください。
迷うところにはおすすめを1つ添え、画面が違うときは今の状態を確認してください。
支払いや許可が必要な操作は、何が起こるかを説明してから確認してください。
この会話の案内だけに適用し、設定ファイルや既存の指示は変更しないでください。`;
const posePrompt = `今できたカピバラの画像を基準に、両手を上げて喜んでいるポーズを1枚作ってください。顔、体型、配色、線、絵柄は揃え、ポーズだけを変えます。背景は透過PNG。全身とまわりの余白を入れ、文字は入れないでください。元の画像は残し、新しい名前で保存して、開けるリンクを案内してください。`;
const seriesPrompt = `同じキャラクターの画像を、新しく5枚、1枚ずつ順番に連続で作ってください。1枚できたら次へ進み、5枚の保存まで続けてください。
この会話で先ほど作ったカピバラの画像を、全5枚に共通する見本として参照してください。見本が確認できないときは、作り始めずに画像の添付をお願いしてください。
顔、体型、目、耳、配色、輪郭線、絵柄を揃え、ポーズだけ変えます。途中で見本を別の画像に置き換えないでください。
1枚目：片手を振っている。
2枚目：ぺこりとおじぎしている。
3枚目：胸の前で両手を合わせ、ありがとうの気持ちを表している。
4枚目：両手を上げて、ばんざいしている。
5枚目：丸くなって眠っている。
全身とまわりの余白を入れ、文字、小物、床、影は入れません。背景は透過PNGにしてください。
1枚の画像に5つのポーズを並べず、別々のPNGファイルを5個作ってください。元の見本は残します。
内蔵の画像生成を使い、各画像を表示して、series-01からseries-05の区別がつく名前で保存してください。同名ファイルがあれば上書きせず、別の名前にします。
最後に保存できた5枚のリンクを、ポーズ名と一緒に一覧にしてください。
利用上限、エラー、必要な確認で止まる場合は、その理由と、保存できた番号・残りの番号を短く伝えてください。未完成の画像を完成扱いにしないでください。`;
function resumeSeriesPrompt(count=0){const n=Math.max(0,Math.min(4,Number(count)||0));return `先ほどお願いした5枚の連続画像づくりを再開してください。私が保存を確認できたのは${n}枚です。\nまず実際の作成・保存状況を確認し、作成済みの画像は作り直さず、まだ作成できていない番号だけ1枚ずつ順番に作ってください。作成済みで私が保存できていない画像は、リンクをもう一度案内してください。\n最初の見本、5つのポーズ、背景透過PNGなどの条件は、先ほどのお願いのままです。見本や条件が確認できないときは、推測せず確認してください。\n元の画像と作成済みのファイルは上書きせず、最後に5枚すべての保存リンクを一覧にしてください。上限やエラーで止まるときは、未完成の番号と理由を教えてください。`;}
const prompts = {creation:creationPrompt,support:supportPrompt,pose:posePrompt,series:seriesPrompt};
function promptText(kind){return kind==='series-resume'?resumeSeriesPrompt(main.querySelector('#saved-count')?.value):prompts[kind];}
function copyDestination(kind){return kind==='support'?'support-paste':kind==='series'||kind==='series-resume'?'series-paste':'paste';}
const steps = {
 ready:{group:0,label:'まずは準備',title:'Codexは、<br>開いていますか？',description:'ここからは、Codexで画像を作ります。<br>お願いする文章は、こちらで用意します。',aside:'あわてなくて、<br>だいじょうぶ。',body:'<p class="note">パソコンのCodexを使います。利用できる機能や料金は、ご自身の契約によって異なります。</p>',next:'copy',button:'開いている',extra:'<button class="quiet" data-go="setup">まだ・開き方がわからない</button><button class="quiet" data-go="support">先に「やさしい案内」をお願いする</button>'},
 setup:{group:0,label:'必要な準備だけ',title:'まずは、<br>アプリを開こう。',description:'準備の手順を別の画面で見られます。<br>このページは、そのまま置いておいてね。',aside:'少しずつで、<br>いいからね。',body:`<a class="button primary full" href="${SITE}/setup" target="_blank" rel="noopener">初期設定の手順を見る ↗</a><p class="note">インストール・作業する場所の作成・会話の始め方を案内します。</p>`,next:'ready',button:'Codexを開いたので戻る',secondary:true},
 support:{group:0,label:'おたすけセットの第一歩',title:'やさしい案内を、<br>お願いしておこう。',description:'これからの会話を、短く、ひとつずつ。<br>そのための文章を用意しました。',aside:'わからない、も<br>教えてね。',body:'<p class="note">今回は会話に文章を渡す方法です。制作スキルの導入は、今後の案内で用意します。</p>',copy:'support',button:'案内のお願いをコピーする',extra:'<button class="quiet" data-go="copy">今回は画像づくりから始める</button>'},
 'support-paste':{group:0,label:'やさしい案内をお願いする',title:'Codexに、<br>貼り付けよう。',description:'Codexの入力欄に、<br>コピーした文章をそのまま貼り付けてね。',aside:'書き直さなくて、<br>だいじょうぶ。',body:'<details class="prompt-details"><summary>貼り付け方がわからないとき</summary><p>Codexの文字を入力するところで、マウスの右ボタンを押し、「貼り付け」を選んでね。</p><p class="note">Macでは、画面上部の「編集」から「ペースト」を選ぶ方法もあります。</p></details>',next:'support-send',button:'貼り付けられた'},
 'support-send':{group:0,label:'やさしい案内をお願いする',title:'文章を、<br>送ってみよう。',description:'Codexの送信ボタンで文章を送ります。<br>返事が来たら、ここに戻ってきてね。',aside:'ここで<br>待ってるよ。',next:'copy',button:'返事が来た。画像を作る'},
 copy:{group:1,label:'画像づくり · 文章の用意',title:'お願い文は、<br>書かなくて大丈夫。',description:'下のボタンを押すと、文章をコピーできます。<br>書き直さなくて大丈夫。',aside:'どんな子に<br>会えるかな。',body:'<p class="note">パソコンのCodexに貼り付けて使います。</p>',copy:'creation',button:'この文章をコピーする',extra:'<a class="quiet" href="#getting-started">Codexをまだ開いていない方はこちら</a>'},
 paste:{group:1,label:'画像づくり · 貼り付ける',title:'Codexに、<br>貼り付けよう。',description:'Codexの入力欄に、<br>コピーした文章をそのまま貼り付けてね。',aside:'そのままで、<br>いいんだよ。',body:'<details class="prompt-details"><summary>貼り付け方がわからないとき</summary><p>Codexの文字を入力するところで、マウスの右ボタンを押し、「貼り付け」を選んでね。</p><p class="note">Macでは、画面上部の「編集」から「ペースト」を選ぶ方法もあります。</p></details>',next:'send',button:'貼り付けられた'},
 send:{group:1,label:'画像づくり · 送る',title:'文章を、<br>送ってみよう。',description:'Codexの送信ボタンで文章を送ります。<br>画像づくりが始まったら、ここに戻ってきてね。',aside:'いよいよ、<br>会えるね。',next:'wait',button:'送れた'},
 wait:{group:1,label:'画像づくり · できあがりを待つ',title:'画像は、<br>出てきましたか？',description:'できあがるまで、少し待ちます。<br>カピバラが見えたら、次へ進もう。',aside:'お茶でも飲んで、<br>ひと休み。',image:'rest',body:'<p class="note">このページから、Codexの進み具合は見えません。ご自身の画面で確認してね。</p>',next:'save',button:'画像が出てきた',extra:'<button class="quiet" data-action="help">まだ出てこない・違う画面になった</button>'},
 save:{group:2,label:'最後に · 手元に残す',title:'できた画像を、<br>開いてみよう。',description:'Codexの返事にある画像ファイルのリンクを押します。',aside:'自分だけの<br>1枚だね。',body:'<details class="prompt-details"><summary>リンクが見つからないとき</summary><p>Codexに「できた画像を開けるリンクを教えて」とお願いしてね。</p></details>',next:'download',button:'画像を開けた'},
 download:{group:2,label:'最後に · 保存する',title:'画像を、<br>保存しよう。',description:'画像の画面にある保存・ダウンロードの操作で、パソコンに残します。',aside:'あとでも<br>会えるように。',body:'<p class="note">画面によって保存の場所が違います。迷ったら、下の「困ったとき」を開いてね。</p>',next:'confirm',button:'保存できた'},
 confirm:{group:2,label:'最後に · 保存できたか確認',title:'保存した画像を、<br>もう一度開こう。',description:'パソコンに残した画像を開いて、<br>カピバラが見えたら、できあがり。',aside:'最後のひとつ、<br>いっしょに確認。',next:'done',button:'保存した画像を開けた'},
 done:{group:3,label:'今日のできた！',title:'ひとつ、<br>できたね。',description:'自分で作った、はじめての1枚。<br>もっと遊びたくなったら、次はこちら。',aside:'できた！<br>うれしいね。',body:'<div class="done-mark">1枚、作って保存できました</div>',next:'series',button:'同じ子で、5枚つづけて作ってみる',extra:'<button class="quiet" data-go="pose">もう1枚だけ作ってみる</button><a class="quiet" href="#rest">今日はここまでにする</a>'},
 series:{group:0,label:'次の遊び · 5枚つづけて',title:'同じ子の、<br>いろんな表情に会おう。',description:'今ある1枚を見本にして、新しく5枚。<br>ポーズはこちらで用意しました。',aside:'この子の仲間、<br>ふやしてみよ。',body:'<ol class="pose-list" aria-label="作る5つのポーズ"><li>手を振る</li><li>ぺこり</li><li>ありがとう</li><li>ばんざい</li><li>おやすみ</li></ol><p class="note">最初の画像を作った、同じ会話で続けます。まだ1枚目がない方は、<a href="#ready">ここから作ってみてね</a>。</p>',next:'series-copy',button:'この5つのポーズで作ってみる',extra:'<a class="quiet" href="#rest">今日はここまでにする</a>'},
 'series-copy':{group:1,label:'5枚つづけて · お願い文',title:'5枚ぶんも、<br>文章は用意済み。',description:'この文章をコピーして、<br>さっきと同じ会話で使ってね。',aside:'1枚ずつ、<br>順番にね。',body:'<p class="note">1枚の中に5つ並べず、別々の画像にします。途中で止まったときの続け方も、このあと案内します。</p>',copy:'series',button:'5枚つくるお願い文をコピーする'},
 'series-paste':{group:1,label:'5枚つづけて · 貼り付ける',title:'さっきと同じ会話に、<br>貼り付けよう。',description:'最初のカピバラがある会話を開き、<br>文字を入力するところに貼り付けてね。',aside:'見本のこの子を、<br>覚えていてね。',body:'<details class="prompt-details"><summary>貼り付け方がわからないとき</summary><p>Codexの文字を入力するところで、マウスの右ボタンを押し、「貼り付け」を選んでね。</p><p class="note">Macでは、画面上部の「編集」から「ペースト」を選ぶ方法もあります。</p></details>',next:'series-send',button:'同じ会話に貼り付けられた'},
 'series-send':{group:1,label:'5枚つづけて · 送る',title:'5枚ぶんのお願いを、<br>送ってみよう。',description:'Codexの送信ボタンで文章を送ります。<br>作り始めたら、ここに戻ってきてね。',aside:'次はどんな<br>ポーズかな。',next:'series-wait',button:'送れた'},
 'series-wait':{group:1,label:'5枚つづけて · できあがりを待つ',title:'5枚、<br>そろいましたか？',description:'Codexの返事で、5枚の画像を確認。<br>まだ作業中なら、そのまま待ってね。',aside:'ゆっくり、<br>待ってるよ。',image:'rest',body:'<p class="note">このページでは、作成の進み具合はわかりません。利用上限などで続けられない場合もあります。</p>',next:'series-save',button:'5枚とも出てきた',extra:'<button class="quiet" data-go="series-resume">途中で止まった・足りない画像がある</button>'},
 'series-resume':{group:1,label:'5枚つづけて · 途中から再開',title:'できた分は、そのまま。<br>続きから作ろう。',description:'手元に保存できた枚数を選んでね。<br>残りを確認してもらう文章が変わります。',aside:'途中からでも、<br>だいじょうぶ。',body:'<label class="count-label" for="saved-count">保存できた枚数</label><select id="saved-count"><option value="0">まだ保存していない</option value="1">1枚</option><option value="2">2枚</option><option value="3">3枚</option><option value="4">4枚</option></select><p class="note">利用上限の案内が出ている場合は、再開できるまで待ってね。</p>',copy:'series-resume',button:'続きから作るお願いをコピーする',extra:'<button class="quiet" data-go="series-wait">作業中なので、待つ画面に戻る</button>'},
 'series-save':{group:2,label:'5枚つづけて · 手元に残す',title:'5枚を、<br>保存しよう。',description:'Codexの返事に並んだ画像のリンクから、<br>1枚ずつ保存してね。',aside:'いろんなこの子を、<br>手元にどうぞ。',body:'<p class="note">まだ保存していない画像からで大丈夫。同じ画像を重ねて保存する必要はありません。</p>',next:'series-confirm',button:'5枚を保存できた',extra:'<button class="quiet" data-go="series-resume">足りない画像やリンクがある</button>'},
 'series-confirm':{group:2,label:'5枚つづけて · 最後の確認',title:'保存した5枚を、<br>開いてみよう。',description:'5つのポーズがそろっているか、<br>1枚ずつ開いて確認してね。',aside:'みんな、<br>そろったかな。',body:'<ol class="pose-list"><li>手を振る</li><li>ぺこり</li><li>ありがとう</li><li>ばんざい</li><li>おやすみ</li></ol>',next:'series-done',button:'5枚とも開いて確認できた',extra:'<button class="quiet" data-go="series-resume">足りない画像があった</button>'},
 'series-done':{group:3,label:'今日のできた！ · 5枚つづけて',title:'5枚、そろったね。<br>小さな作品集のできあがり。',description:'同じ子でも、ポーズが違うと楽しいね。<br>お気に入りの1枚は、どの子かな。',aside:'いっしょにできて、<br>うれしいな。',body:'<div class="done-mark">新しく5枚、作って保存できました</div>',next:'rest',button:'今日はここまでにする',extra:'<a class="quiet" href="#workshop">勉強会の教材で、もっと楽しむ</a>'},
 pose:{group:1,label:'もう1枚、楽しむ',title:'同じ子で、<br>違うポーズを。',description:'さっき画像を作った会話で続けます。<br>顔や色は揃えて、ポーズだけ変えよう。',aside:'今度は<br>ばんざーい。',copy:'pose',button:'続きのお願いをコピーする'},
 rest:{group:3,label:'今日は、おしまい',title:'また、<br>一緒に作ろう。',description:'今日の「できた！」は、ちゃんと残ったね。<br>続きをやりたくなったら、いつでもどうぞ。',aside:'おつかれさま。<br>また会おうね。',image:'rest',body:`<a class="button primary full" href="#workshop">勉強会の教材を見てみる</a>`,extra:'<a class="quiet" href="#home">入口に戻る</a>'}
};
let trail = [];
let previousFocus;
let canStore = true;
function readProgress(){try{const value=JSON.parse(localStorage.getItem(KEY)||'null');return value&&steps[value.step]?value:null}catch{return null}}
let saved = readProgress();
function persist(step){saved={step};try{localStorage.setItem(KEY,JSON.stringify(saved))}catch{canStore=false}}
function go(step){const current=location.hash.slice(1)||'home';if(current!==step)trail.push(current);if(steps[step])persist(step);location.hash=step;}
const button=(label,step,secondary=false)=>`<button class="button ${secondary?'outline':'primary'} full" data-go="${step}">${label}<span aria-hidden="true">→</span></button>`;
function home(){return `<section class="codex-hero"><div class="hero-copy"><span class="eyebrow">コピーして、そのまま使えるCodex</span><h1><span>コピーして、</span><span>貼り付けて。</span><span>Codexで作ろう。</span></h1><p class="lead">お願いする文章は、用意してあります。<br>まずはそのまま、使ってみよう。</p></div><figure class="mascot-scene"><div class="mascot-greeting">……ふむ。<br>いっしょに、やってみよう。</div><div class="mascot-portrait"><img src="images/mascot/wave.png" alt="緑のくま耳フードを着てランタンを持つもちスラくま。頭の上には小さな芽ちゃん" width="1254" height="1254" fetchpriority="high"></div><figcaption>案内役のもちスラくまと、芽ちゃん</figcaption></figure></section>
<section class="path-section" aria-labelledby="path-title"><div class="path-heading"><h2 id="path-title">迷ったら、まずは1枚。</h2><p>コピーするボタンから始められます。</p></div><div class="path-grid">
<a class="path-card path-first" href="#copy"><span class="path-kicker">まずはこれがおすすめ</span><h3>コピーして1枚作る</h3><p>文章を考えなくて大丈夫。<br>かわいいカピバラを作ってみよう。</p><span class="path-action">使う文章を開く <span aria-hidden="true">→</span></span></a>
<a class="path-card path-make" href="#series"><span class="path-kicker">1枚作れたら、次はこちら</span><h3>同じ子で5枚作る</h3><p>ポーズも文章も用意済み。<br>続きも、コピペで試せます。</p><span class="path-action">5枚の作り方を開く <span aria-hidden="true">→</span></span></a>
<a class="path-card path-study" href="#workshop"><span class="path-kicker">動画で見たい・見返したい方へ</span><h3>勉強会・復習</h3><p>講義のスライド、動画、まとめ。<br>見たいところから開けます。</p><span class="path-action">教材・録画を見る <span aria-hidden="true">→</span></span></a>
</div><p class="note welcome-note">Codexの準備がまだの方は、<a href="#getting-started">アプリの準備はこちら</a>。</p></section>${saved?`<div class="resume home-resume"><span>画像づくりの続きも、ここにあるよ。</span><a href="#${saved.step}">前の続きから進む →</a></div>`:''}<nav class="quick-links" aria-label="よく使う教材"><span>すぐに開く</span><a href="${SITE}/prompt-maker" target="_blank" rel="noopener">お願い文メーカー ↗</a><a href="${SITE}/skills" target="_blank" rel="noopener">スキル図書館 ↗</a></nav>`;}
function gettingStarted(){return `<a class="back-link" href="#home">← 入口に戻る</a><section class="start-panel"><div class="start-copy"><span class="eyebrow">アプリの準備が必要なときだけ</span><h1>Codexが開いたら、<br>そのまま始めよう。</h1><p class="description">使う文章はこちらで用意しました。<br>開いている方は、すぐにコピーできます。</p><a class="button primary" href="#copy">使う文章を開く →</a><details class="prompt-details"><summary>まだCodexを開いていない方へ</summary><p>インストールから最初の画面まで、図解で案内します。</p><a class="button outline" href="${SITE}/setup" target="_blank" rel="noopener">アプリの準備を見る ↗</a><p class="note">図解は別の画面で開きます。Codexを開けたら、ここに戻ってきてね。</p></details></div><aside class="start-mascot"><div class="mascot-portrait"><img src="images/mascot/guide.png" width="1254" height="1254" alt="ランタンを持って案内するもちスラくま"></div><p>文章は、おまかせ。<br>そのまま使ってね。</p></aside></section>`;}
function makeHub(){return `<a class="back-link" href="#home">← 入口に戻る</a><header class="workshop-title"><span class="eyebrow">Codexで、画像を作る</span><h1>まずは1枚。<br>慣れたら、5枚。</h1><p>作りたいものを選んで、文章をコピー。<br>書き直さず、そのまま使えます。</p></header><div class="make-grid"><a class="make-card" href="#copy"><div class="make-sample"><img src="images/wave.png" alt="最初に作るカピバラの見本" width="130" height="165"><span>できあがりの見本</span></div><div><span class="eyebrow">まずは、ここから</span><h2>かわいい1枚を作る</h2><p>コピーから画像の保存まで、<br>今やることをひとつずつ。</p><span class="path-action">1枚作ってみる →</span></div></a><a class="make-card" href="#series"><div class="series-count" aria-hidden="true"><b>5</b><span>つのポーズ</span></div><div><span class="eyebrow">1枚作れたら、次はこちら</span><h2>同じ子で、5枚つづけて</h2><p>顔や色はそのまま。<br>ポーズを変えて、小さな作品集に。</p><span class="path-action">5枚つづけて作る →</span></div></a></div><p class="note welcome-note">作る画像は見本と少しずつ違います。画像づくりには、パソコンのCodexを使います。</p><p class="welcome-note"><a href="#getting-started">アプリの準備がまだの方はこちら →</a></p>`;}
function workshop(){const resources=[['講師と一緒に','講義のスライド','勉強会で使う教材を、順番に。','/live'],['録画で見返す','第1回のアーカイブ','カピバラづくりの実演を、もう一度。',RECORDING],['すぐに試す','お願いする文章を作る','好みを選んで、実演の文章をコピー。','/prompt-maker'],['さくっと復習','画像づくりのまとめ','同じキャラクターを続けて作るコツ。','/recap']];return `<button class="back-link" data-go="home">← 入口に戻る</button><header class="workshop-title"><span class="eyebrow">勉強会に参加・復習する</span><h1>見たいところから、<br>何度でも。</h1><p>一緒に作る日も、あとから見返す日も。</p></header><div class="resource-grid">${resources.map(([tag,title,desc,path])=>`<a class="resource" href="${path.startsWith('http')?path:SITE+path}" target="_blank" rel="noopener"><small>${tag}</small><h2>${title}</h2><p>${desc}</p><span class="arrow">開く ↗</span></a>`).join('')}</div><p class="note welcome-note">教材は現在のサイトを別の画面で開きます。</p><p class="welcome-note"><a href="#ready">ゆっくり、1枚から始めたい方はこちら →</a></p>`;}
function renderStage(id){const s=steps[id];const complete=s.group===3;const progressLabels=id.startsWith('series')?['用意','5枚つくる','保存する']:['準備','画像を作る','保存する'];return `<div class="journey-header"><button class="back-link" data-action="back">← ひとつ戻る</button><ol class="progress" aria-label="全体の進み方">${progressLabels.map((label,i)=>`<li class="${s.group===i||complete?'active':''}" ${s.group===i?'aria-current="step"':''}><i>${i<s.group?'✓':i+1}</i>${label}</li>`).join('')}</ol></div><section class="stage ${complete?'success':''}"><aside class="companion"><img src="images/${s.image==='rest'?'rest':'wave'}.png" width="190" height="260" alt="${s.image==='rest'?'休んでいるカピバラ':'手を振るカピバラ'}"><p>${s.aside}</p></aside><div class="stage-content"><span class="eyebrow">${s.label}</span><h1 tabindex="-1">${s.title}</h1><p class="description">${s.description}</p>${s.body||''}${s.copy?`<button class="button primary full" data-copy="${s.copy}">${s.button} <span aria-hidden="true">⧉</span></button><p id="copy-status" class="status" role="status"></p><div id="manual-copy-next"></div><details class="prompt-details"><summary>文章の中身を見る</summary><textarea readonly aria-label="コピーするお願い文" spellcheck="false">${s.copy==='series-resume'?resumeSeriesPrompt(0):prompts[s.copy]}</textarea></details>`:s.next?button(s.button,s.next,s.secondary):''}${s.extra||''}</div></section><div class="stage-foot"><p class="note">${canStore?'このブラウザで、続きから再開できます。':'このブラウザでは進み具合を保存できません。このページを開いたままにしてください。'}</p><button class="helper-link" data-action="help"><b aria-hidden="true">?</b>困ったとき</button></div>`;}
function render(focus=true){const id=location.hash.slice(1)||'home';main.innerHTML=id==='workshop'?workshop():id==='getting-started'?gettingStarted():id==='make'?makeHub():steps[id]?renderStage(id):home();document.title=(id==='workshop'?'勉強会・復習':id==='getting-started'?'アプリの準備':id==='make'?'画像を作る':steps[id]?steps[id].title.replaceAll('<br>',''):'もちスラくまと、ひとつずつ。')+'｜Codexの教科書';document.querySelectorAll('[data-nav]').forEach(link=>{const active=link.dataset.nav===(steps[id]?'make':id);if(active)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});if(focus){(main.querySelector('h1')||main).setAttribute('tabindex','-1');(main.querySelector('h1')||main).focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}if(steps[id])persist(id);}
async function copy(kind,trigger){const text=promptText(kind);const next=copyDestination(kind);trigger.disabled=true;try{await navigator.clipboard.writeText(text);document.querySelector('#announcement').textContent='コピーできました。次はCodexに貼り付けます。';go(next);}catch{const details=main.querySelector('details');details.open=true;const field=details.querySelector('textarea');field.focus();field.select();document.querySelector('#copy-status').textContent='自動コピーができませんでした。選ばれた文章の上で右クリックして「コピー」を選んでね。';document.querySelector('#manual-copy-next').innerHTML=button('自分でコピーできた',next);trigger.disabled=false;}}
function openHelp(){previousFocus=document.activeElement;dialog.showModal();}
function closeHelp(){dialog.close();previousFocus?.focus();}
const help={screen:`今の操作はお休みして、<a href="${SITE}/setup" target="_blank" rel="noopener">初期設定の図解 ↗</a>を見てみよう。画面が違うときは、無理に同じボタンを探さなくて大丈夫。元の案内はここに残っています。`,image:'Codexが作業中なら、そのまま待ってみよう。止まったままなら、Codexに「今どこまでできていますか？」と聞いてみてね。使えない機能や利用上限の案内があるときは、その内容を先に確認します。',permission:'何を許可するのか、料金がかかるのか。意味がわからないまま押さず、いったん止まろう。閉じられる案内なら閉じてから、内容を確認してね。'};
document.addEventListener('click',event=>{const anchor=event.target.closest('a');if(anchor&&anchor.getAttribute('href')?.startsWith('#')&&anchor.getAttribute('href')!=='#main'&&!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&!event.altKey){event.preventDefault();go(anchor.getAttribute('href').slice(1));return;}const target=event.target.closest('button');if(!target)return;if(target.dataset.go)return go(target.dataset.go);if(target.dataset.copy)return copy(target.dataset.copy,target);if(target.dataset.help){dialog.querySelectorAll('[data-help]').forEach(b=>b.setAttribute('aria-pressed',String(b===target)));document.querySelector('#help-answer').innerHTML=help[target.dataset.help];return;}if(target.dataset.action==='help')openHelp();if(target.dataset.action==='close-help')closeHelp();if(target.dataset.action==='back'){const fallback=location.hash.startsWith('#series')?(location.hash==='#series'?'done':'series'):(location.hash==='#ready'?'make':'ready');location.hash=trail.pop()||fallback;}});
document.addEventListener('change',event=>{if(event.target.id==='saved-count'){const field=main.querySelector('textarea');if(field)field.value=resumeSeriesPrompt(event.target.value);}});
window.addEventListener('hashchange',()=>render());
render(false);
